In [7]:
%run main.py

[lines] [[[ 6.6600000e+02  1.5009831e+00]]

 [[-3.8800000e+02  3.0194197e+00]]

 [[ 2.8400000e+02  5.2359879e-02]]

 [[ 3.5800000e+02  1.5184364e+00]]

 [[-4.4400000e+02  2.9146998e+00]]

 [[-3.3700000e+02  3.1066861e+00]]

 [[ 2.1600000e+02  1.5707964e-01]]

 [[ 3.1000000e+02  1.5184364e+00]]

 [[ 4.1100000e+02  1.5184364e+00]]

 [[ 2.5300000e+02  8.7266460e-02]]

 [[ 2.6600000e+02  1.5184364e+00]]

 [[ 3.0700000e+02  0.0000000e+00]]

 [[ 5.4400000e+02  1.5009831e+00]]

 [[-4.1600000e+02  2.9845130e+00]]

 [[ 4.7100000e+02  1.5184364e+00]]

 [[ 2.2800000e+02  1.3962634e-01]]

 [[-4.3400000e+02  2.9321532e+00]]

 [[-3.6000000e+02  3.0543261e+00]]

 [[ 2.2700000e+02  1.5184364e+00]]

 [[ 6.2000000e+02  1.5009831e+00]]]
[  0 114 193 273 352 431 509 588 666 700]
S : 0
rlt_points [  0 114 193 273 352 431 509 588 666 700]
rlt_points roll [700   0 114 193 273 352 431 509 588 666]
rlt_points_ect [114  79  80  79  79  78  79  78  34]
ect_median 79.0
ect_norm [1.44303797 1.         1.01265823 1

error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


In [9]:
a = np.array([100, 100])

In [10]:
a / 2

array([50., 50.])

In [9]:
import numpy as np
import cv2 as cv2

import time
import os
import numpy as np
import cv2 as cv2
import chess.engine
from matplotlib import pyplot as plt
from get_chess_plate import *
from scipy import signal
from skimage.metrics import structural_similarity
from classes.game import *
from classes.video_capture import *
from classes.image_logger import *

In [19]:
frame = cv2.imread(
        "C:/Users/Romaric/DataScience/Echecs Vision/echec_vision/images/Suivis 2/9.jpg")

In [20]:
plate = get_chess_plate(frame)
plate.show()
cv2.waitKey(0)

-1

In [29]:
a = [600, 678, 56, 789, 602, 567, 678]

In [30]:
b = [np.array([[35, 67]]), np.array([[37, 12]]), np.array([[45, 89]]), np.array([[32, 56]]), np.array([[13, 54]]), np.array([[25, 24]]), np.array([[25, 64]])]

In [32]:
sorted(zip(a,b))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()